<a href="https://colab.research.google.com/github/AhmedEssamK/UdemyNLP/blob/Deep-Learning/Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [6]:
X = iris.data

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
#class 0 --> [1,0,0]
#class 1 --> [0,1,0]
#class 2 --> [0,0,1]

In [11]:
from keras.utils import to_categorical

In [12]:
y = to_categorical(y)

In [13]:
y.shape

(150, 3)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
scaler_object = MinMaxScaler()

In [20]:
scaler_object.fit(X_train)

MinMaxScaler()

In [21]:
scaled_X_train = scaler_object.transform(X_train)

In [22]:
scaled_X_test = scaler_object.transform(X_test)

In [23]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 8)                   │              40 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 3)                   │              27 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 139 (556.00 B)

 Trainable params: 139 (556.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
4/4 - 1s - 364ms/step - accuracy: 0.3500 - loss: 1.0979
Epoch 2/150
4/4 - 0s - 7ms/step - accuracy: 0.3600 - loss: 1.0959
Epoch 3/150
4/4 - 0s - 8ms/step - accuracy: 0.3700 - loss: 1.0939
Epoch 4/150
4/4 - 0s - 7ms/step - accuracy: 0.3700 - loss: 1.0925
Epoch 5/150
4/4 - 0s - 7ms/step - accuracy: 0.3700 - loss: 1.0909
Epoch 6/150
4/4 - 0s - 7ms/step - accuracy: 0.3700 - loss: 1.0892
Epoch 7/150
4/4 - 0s - 7ms/step - accuracy: 0.3600 - loss: 1.0874
Epoch 8/150
4/4 - 0s - 8ms/step - accuracy: 0.3700 - loss: 1.0853
Epoch 9/150
4/4 - 0s - 11ms/step - accuracy: 0.3700 - loss: 1.0832
Epoch 10/150
4/4 - 0s - 7ms/step - accuracy: 0.3600 - loss: 1.0810
Epoch 11/150
4/4 - 0s - 7ms/step - accuracy: 0.3400 - loss: 1.0790
Epoch 12/150
4/4 - 0s - 7ms/step - accuracy: 0.3400 - loss: 1.0767
Epoch 13/150
4/4 - 0s - 8ms/step - accuracy: 0.3100 - loss: 1.0748
Epoch 14/150
4/4 - 0s - 8ms/step - accuracy: 0.3100 - loss: 1.0728
Epoch 15/150
4/4 - 0s - 14ms/step - accuracy: 0.3200 - loss: 1.0710


In [30]:
model.predict(scaled_X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[1.73534304e-02, 4.90849972e-01, 4.91796583e-01],
       [9.66691613e-01, 2.21341643e-02, 1.11742867e-02],
       [3.15701618e-04, 2.90159523e-01, 7.09524751e-01],
       [1.83001384e-02, 4.78960544e-01, 5.02739370e-01],
       [6.79817237e-03, 4.23513681e-01, 5.69688141e-01],
       [9.41892564e-01, 3.89456376e-02, 1.91618633e-02],
       [8.29585195e-02, 5.22363663e-01, 3.94677758e-01],
       [2.31237337e-03, 3.31142783e-01, 6.66544914e-01],
       [5.16907731e-03, 4.68013734e-01, 5.26817143e-01],
       [3.78219858e-02, 5.28798461e-01, 4.33379591e-01],
       [6.25950377e-03, 3.88111383e-01, 6.05629146e-01],
       [9.29294884e-01, 4.57314551e-02, 2.49736514e-02],
       [9.62869108e-01, 2.44940426e-02, 1.26367984e-02],
       [9.35907722e-01, 4.15713079e-02, 2.25209668e-02],
       [9.73617613e-01, 1.74953993e-02, 8.88696406e-03],
       [2.41419543e-02, 4.54867542e-01, 5.20990431e-01],
       [1.48805906e-03, 3.34923714e-01, 6.63588226e-01],
       [3.32865082e-02, 5.45955

In [34]:
predictions = np.argmax(model.predict(scaled_X_test), axis=-1)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 


In [35]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [36]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0,  5, 10],
       [ 0,  0, 16]])

In [37]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.33      0.50        15
           2       0.62      1.00      0.76        16

    accuracy                           0.80        50
   macro avg       0.87      0.78      0.75        50
weighted avg       0.88      0.80      0.77        50



In [39]:
print(accuracy_score(y_test.argmax(axis=1), predictions))

0.8


In [40]:
model.save('myfirstmodel.h5')

In [42]:
from keras.models import load_model
new_model = load_model('myfirstmodel.h5')